name: CI

on:
  push:
    #branches: [ "development" ]
  pull_request:
    #branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup NodeJS
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    # Install dependencies
    - name: Install dependencies
      run: |
        npm ci

    # Build project
    - name: Build Project
      run: |
        npm run build

    - name: Configure Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    # Check with prettier and commit changes to branch.
    - name: Run and format prettier
      env:
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx prettier . --write
        git add .
        git commit -m "Format code with Prettier"
        git push


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup NodeJS
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    # Install dependencies
    - name: Install dependencies
      run: |
        npm ci

    # Build project
    - name: Build Project
      run: |
        npm test
    
